This is the homework for week 2! The prompt is to use NumPy (or sagemath) to determine if a list of vectors forms an orthogonal / orthonormal basis for a vector space, compute inner products, multiply matrices, and compute LU and spectral decompositions.

Problem 1: Build a function to take two vectors with real-valued entries and compute their inner product. 

In [ ]:
def ip(v1,v2):

    #ip_out is the running sum of our terms
    ip_out = 0

    #quality control to make sure that v1 and v2 are the same length
    if len(a) == len(b):

        #the for loop indexes the rows in each vector
        for i in range(len(v1)):
            
            #this next line computes the ith sum in our inner product calculation
            ip_out += v1[i]*v2[i]
        
        #the return statement ends the function and outputs the inner product of both vectors
        return ip_out
    else:
        return print('Your vectors are not the same length!')

#put test cases here
a = [1,2,3,-1]
b = [-2,1,1,3]

#print the output
print(f'The inner product of {a} and {b} is {ip(a,b)}.')

The inner product of [1, 2, 3, -1] and [-2, 1, 1, 3] is 0.


Problem 2: Build a function which checks if two matrices can be multiplied and then multiplies them.

In [16]:
import numpy as np

#initialize matrices
A = np.array( [ [3,2], [-1,0], [3,3]] )
B = np.array( [ [3,2], [-1,0] ] )

#check if we can multiply the matrices
def canMult(A,B):
    if np.shape(A)[1] == np.shape(B)[0]:
        return True
    else:
        return False

#multiply the matrices
def mult(A,B):
    m = np.shape(A)[0]
    r = np.shape(B)[1]
    sh = (m,r)
    C = np.zeros(shape=sh)

    if canMult(A,B) is True:
        for i in range(r):
            for j in range(m):
                C[j,i] = ip(A[j,:],B[:,i])

        return C
    else:
        return print('Cannot multiply these matrices.')

mult(A,B)

array([[ 7.,  6.],
       [-3., -2.],
       [ 6.,  6.]])

Problem 3: Build a function which takes A and computes $A^T$.

In [21]:
def trpose(A):
    #get the number of rows and columns
    n1 = np.shape(A)[0]
    n2 = np.shape(A)[1]
    #create the shape of the transpose
    sh = (n2,n1)

    #initialize an empty matrix
    AT = np.zeros(shape=sh)

    #fill in the data
    for i in range(n2): #for i in the range of the number of rows in A^T
        for j in range(n1): #for j in range of the number of cols in A^T
            #make the a_ijth entry of A^T the a_jith entry of A
            AT[i,j] = A[j,i]
    return AT

A = np.array( [ [3,2], [-1,0], [3,3]] )
trpose(A)

array([[ 3., -1.,  3.],
       [ 2.,  0.,  3.]])

Problem 4: Build a function which determines if a list of vectors is an orthogonal or orthonormal basis by computing $A^T A$ and checking if it is diagonal / I. (Hint: Use your function from problem 3!)

In [35]:
def isDiag(A):
    #we want to figure out if a matrix is diagonal, and thus orthogonal and orthonormal.
    #the main definition for diagonality is, for i not equal to j, that all a_ij = 0

    #get the shape
    n1 = np.shape(A)[0]
    n2 = np.shape(A)[1]

    is_diag = True
    is_ortho = True
    for i in range(n1):
        for j in range(n2):
            #we have the ij indexer, and so now, we want to check every entry, i not equal j
            if i != j:
                #check to see if a_ij is not zero. if it is, we're done for both orthogonality and orthonormality. 
                if A[i,j] != 0:
                    is_diag = False
                    break #ends the loop early
            else: #if i is j, we want to check that a_ij = 1
                if A[i,j] != 1:
                    is_ortho = False
                    if A[i,j] == 0:
                        is_diag = False
    
    if is_ortho is True:
        return 'Orthonormal'
    elif is_diag is True:
        return 'Orthogonal'
    else:
        return 'Neither'



#this is the big function that actually gets called and determines orthogonality/orthonormality
def isOrth(A):
    #compute A^T
    AT = trpose(A)

    #multiply A^T * A
    C = mult(AT,A)

    if isDiag(C) == 'Orthonormal':
        return print(f'{A} is an orthonormal basis for V.')
    elif isDiag(C) == 'Orthogonal':
        return print(f'{A} is an orthogonal basis but not an orthonormal basis for V.')
    else:
        return print(f'{A} is not an orthogonal or orthonormal basis for V.')


A = np.array( [ [1,0], [1,1]] )
isOrth(A)

[[1 0]
 [1 1]] is not an orthogonal or orthonormal basis for V.


Problem 5: Use Numpy's internal tools to compute the eigenvectors and eigenvalues of A, and then build a function which outputs the spectral decomposition of A.